version: '2'
services:

  pootle:
    restart: always
    build: .
    volumes:
     - ./volumes/conf:/var/www/pootle/.pootle
     - ./volumes/serge:/var/serge
     - /var/www/pootle
    ports:
     - "8000:8000"
    expose:
     - "8000"
    depends_on:
     - postgres
     - redis
    links:
     - redis:redis
    env_file: .env


  redis:
    restart: always
    image: redis:3.2.8
    expose:
      - "6379"


  postgres:
    restart: always
    image: postgres:9.4.11
    volumes_from:
      - data
    volumes:
      - ./backups/postgresql:/backup
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    expose:
      - "5432"


  data:
    restart: always
    image: alpine
    volumes:
      - /var/lib/postgresql
    command: "true"
